# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "bundles/fosckeditor"
    js_path:   "bundles/fosckeditor/ckeditor.js"
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
